from tkinter import *
fenetre = Tk ()
fenetre. geometry('1000x300')
fenetre. title ('Gestion des bus ')
fenetre. resizable (height=True, width=True)

label = Label(fenetre, text= "Bus", font=("Verdana", 10))
label. place(x='5', y= '5')
label = Label(fenetre, text= "Immatriculation :")
label. place(x='53', y= '50')
label = Label(fenetre, text= "Date d'acquisition :")
label. place(x='50', y= '80')
label = Label(fenetre, text= "Capacité :")
label. place(x='70', y= '110')
label = Label(fenetre, text= "Nombre de locations :")
label. place(x='403', y= '50')
label = Label(fenetre, text= "Montant des locations :")
label. place(x='400', y= '80')
label = Label(fenetre, text= "3")
label. place(x='597', y= '50')
label = Label(fenetre, text= "550.000")
label. place(x='583', y= '80')
bouton = Button(fenetre, text="Ajouter" , font=("Verdana", 10))
bouton.place(x='759', y= '50')
bouton = Button(fenetre, text="Supprimer" , font=("Verdana", 10))
bouton.place(x='750', y= '80')
bouton = Button(fenetre, text="Annuler" , font=("Verdana", 10))
bouton.place(x='757', y= '110')
bouton = Button(fenetre, text="Locations" , font=("Verdana", 10))
bouton.place(x='750', y= '140')
entree_Im = Entry(fenetre)
entree_Im.place(x='220', y= '50')
entree_Da = Entry(fenetre)
entree_Da.place(x='220', y= '80')
entree_Ca = Entry(fenetre)
entree_Ca.place(x='220', y= '110')
fenetre. mainloop()

